builders:

  copyBuilder:
    import: "package:proto_builder/proto_builder.dart"
    builder_factories: ["copyBuilder"]
    build_extensions: {'^protos/{{}}.proto': ['lib/generated/{{}}.proto.copy']}
    auto_apply: root_package
    build_to: source

targets:
  $default:
    sources:
      - protos/**
      - lib/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
        