name: example
publish_to: none
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  built_value: ^8.1.4
  fixnum: ^1.0.0
  grpc: ^3.0.2
  path: ^1.8.1
  proto_builder:
    path: ../

dev_dependencies:
  build_runner: ^2.1.8
  built_value_generator: ^8.1.4
