name: proto_builder
description: A Dart builder that integrates the protobuf compiler for a integrated developer experience
version: 0.1.0
homepage: https://github.com/dropbear-software/proto_builder

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.8
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  build: ^2.2.1
  scratch_space: ^1.0.1
